# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c17d8c2ff80e01006d4655765c6da4e7cd697e255c5f849143be85e3f5ff6d6bcc7d4126d34780043376b168aed34aafc49c8c8764bd16f2d915e0a1e2d6424

test:
  secret_key_base: 5f40ea1226f49569b80d9be3f7933e06c88c7c5246271e74cc86dcaf249e09a137c80d924273113d90de7248430b7559f1cc458c2c486a5f7e8e89bf3ac89177

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
